// official-parallel-nutrients — replica of https://echarts.apache.org/examples/zh/editor.html?c=parallel-nutrients
// title: Parallel Nutrients / titleCN: 营养结构（平行坐标）
// 7637 USDA foods drawn as polylines across 15 vertical nutrient axes (`parallel` + `layout:'vertical'`),
// coloured by their food group through a PIECEWISE `visualMap` on dimension 1; the 25 group colours are
// generated by walking the hue of '#5A94DF' with `echarts.color.modifyHSL`. `progressive: 500`,
// `animation: false`, near-zero line opacity (0.05) — the shape is the density of 7.6k overlaid lines.
//
// DEVIATIONS from the official source:
//   - DATA INLINED. Upstream wraps everything in `$.get(ROOT_PATH + '/data/asset/data/nutrients.json',
//     function (data) { ... })`. The fetch is dropped; the JSON (assets/data/nutrients.json, mirrored from
//     the official asset tree, 7637 rows × 17 columns) is spliced into the web pane's script verbatim and
//     the callback body (`normalizeData(data); myChart.setOption((option = getOption(data)))`) runs at the
//     top level. Everything else in the web pane — `indices`, `schema`, `normalizeData`, `getOption`,
//     `echarts.color.modifyHSL` — is the example's own code, untouched.
//   - TypeScript-only syntax removed from the web pane (`: string[]`, `Record<string, number>`,
//     `item as string`, `as echarts.EChartsOption`) and the trailing `export {};` dropped — a bare export
//     is a SyntaxError in a classic script and would kill the page.
//   - NATIVE pane: `normalizeData` / `getOption` are JS closures, so the Swift side recomputes what they
//     produce — null→0 coercion of the 14 numeric columns, the food-group list in first-seen order, and the
//     25 hue-stepped colours via ZRenderKit's `color.modifyHSL` (the same zrender function the web pane
//     calls). The resulting `option` is the same option, key for key.
//   - CANVAS SIZE. The example needs a TALL pane, and it is the option itself that says so: the
//     piecewise visualMap has 25 categories, which at echarts' default itemHeight (14) + itemGap (10)
//     is 25*14 + 24*10 = 590px of legend, from `top: 20` — ~610px. Upstream's own page
//     (upstream/echarts/test/parallel-nutrients.html) gives it a 1000px-tall container for exactly
//     that reason. The gallery's usual ~460px would clip 15 of the 25 food groups and squash the 15
//     stacked (`layout: 'vertical'`) axes into ~25px each, so this demo renders at 720x640. Both panes
//     get the same size, so the native-vs-web diff is unaffected.
//   - No timeline: the example is a single `setOption`, so there is no `drive`.
import Foundation
import ZRenderKit

// The raw asset text, spliced straight into the web pane's script (the page cannot reach the filesystem).
private let nutrientsRawJSON: String = {
    let url = Upstream.repoRoot.appendingPathComponent("assets/data/nutrients.json")
    return (try? String(contentsOf: url, encoding: .utf8)) ?? "[]"
}()

// The Swift half of upstream's `normalizeData`: rows with the 14 nutrient columns coerced to numbers
// (`parseFloat(item) || 0` — the asset has 12507 nulls), the food groups in first-seen order, and one
// colour per group stepped around the hue wheel from '#5A94DF'. A parse failure degrades to empty
// (the pane renders blank rather than crashing).
private let nutrientsNormalized: (rows: [[Any]], groups: [String], colors: [String]) = {
    let url = Upstream.repoRoot.appendingPathComponent("assets/data/nutrients.json")
    guard let data = try? Data(contentsOf: url),
          let raw = (try? JSONSerialization.jsonObject(with: data)) as? [[Any]] else {
        return ([], [], [])
    }
    // indices = { name: 0, group: 1, id: 16 } — every OTHER column is a nutrient, in grams.
    let nameIdx = 0, groupIdx = 1, idIdx = 16

    var rows: [[Any]] = []
    rows.reserveCapacity(raw.count)
    var groups: [String] = []
    for row in raw {
        var r = row
        for i in r.indices where i != nameIdx && i != groupIdx && i != idIdx {
            let v: Double
            if let n = r[i] as? NSNumber { v = n.doubleValue }
            else if let s = r[i] as? String { v = Double(s) ?? 0 }
            else { v = 0 }                       // null / anything else → 0
            r[i] = v.isFinite ? v : 0
        }
        rows.append(r)
        if r.count > groupIdx, let g = r[groupIdx] as? String, !groups.contains(g) { groups.append(g) }
    }

    // `const hStep = Math.round(300 / (groupCategories.length - 1))` → 13 for the asset's 25 groups.
    let hStep = groups.count > 1 ? (300.0 / Double(groups.count - 1)).rounded() : 0
    var colors: [String] = []
    colors.reserveCapacity(groups.count)
    for i in 0..<groups.count {
        colors.append(ZRenderKit.color.modifyHSL("#5A94DF", .number(hStep * Double(i))) ?? "#5A94DF")
    }
    return (rows, groups, colors)
}()

// `parallelAxis` — upstream lists dim 16 (id, `scale: true`) first, then the nutrient dims in the
// example's own order (2, 4, 3, 5, 6, ... 15). `name` comes from `schema[dim].name`.
private let nutrientsParallelAxis: [[String: Any]] = [
    ["dim": 16.0, "name": "id", "scale": true, "nameLocation": "end"],
    ["dim": 2.0, "name": "protein", "nameLocation": "end"],
    ["dim": 4.0, "name": "sodium", "nameLocation": "end"],
    ["dim": 3.0, "name": "calcium", "nameLocation": "end"],
    ["dim": 5.0, "name": "fiber", "nameLocation": "end"],
    ["dim": 6.0, "name": "vitaminc", "nameLocation": "end"],
    ["dim": 7.0, "name": "potassium", "nameLocation": "end"],
    ["dim": 8.0, "name": "carbohydrate", "nameLocation": "end"],
    ["dim": 9.0, "name": "sugars", "nameLocation": "end"],
    ["dim": 10.0, "name": "fat", "nameLocation": "end"],
    ["dim": 11.0, "name": "water", "nameLocation": "end"],
    ["dim": 12.0, "name": "calories", "nameLocation": "end"],
    ["dim": 13.0, "name": "saturated", "nameLocation": "end"],
    ["dim": 14.0, "name": "monounsat", "nameLocation": "end"],
    ["dim": 15.0, "name": "polyunsat", "nameLocation": "end"]
]

extension EChartsDemoRegistry {
    static let official_parallel_nutrients = EChartsDemo(
        name: "official-parallel-nutrients", category: "parallel",
        summary: "营养结构（平行坐标） — Parallel Nutrients",
        width: 720, height: 640,   // 25-category piecewise visualMap needs ~610px — see header
        nativeSupported: true,
        collection: .official,
        webOptionJS: #"""
const indices = {
  name: 0,
  group: 1,
  id: 16
};
const schema = [
  { name: 'name', index: 0 },
  { name: 'group', index: 1 },
  { name: 'protein', index: 2 },
  { name: 'calcium', index: 3 },
  { name: 'sodium', index: 4 },
  { name: 'fiber', index: 5 },
  { name: 'vitaminc', index: 6 },
  { name: 'potassium', index: 7 },
  { name: 'carbohydrate', index: 8 },
  { name: 'sugars', index: 9 },
  { name: 'fat', index: 10 },
  { name: 'water', index: 11 },
  { name: 'calories', index: 12 },
  { name: 'saturated', index: 13 },
  { name: 'monounsat', index: 14 },
  { name: 'polyunsat', index: 15 },
  { name: 'id', index: 16 }
];

const groupCategories = [];
const groupColors = [];

// DEVIATION: upstream fetches this with
//   $.get(ROOT_PATH + '/data/asset/data/nutrients.json', function (data) { ... });
// The gallery inlines the same asset and runs the callback body at the top level.
const nutrientsData = \#(nutrientsRawJSON);

normalizeData(nutrientsData);
myChart.setOption((option = getOption(nutrientsData)));

function normalizeData(originData) {
  const groupMap = {};
  originData.forEach(function (row) {
    const groupName = row[indices.group];
    if (!groupMap.hasOwnProperty(groupName)) {
      groupMap[groupName] = 1;
    }
  });

  originData.forEach(function (row) {
    row.forEach(function (item, index) {
      if (
        index !== indices.name &&
        index !== indices.group &&
        index !== indices.id
      ) {
        // Convert null to zero, as all of them under unit "g".
        row[index] = parseFloat(item) || 0;
      }
    });
  });

  for (const groupName in groupMap) {
    if (groupMap.hasOwnProperty(groupName)) {
      groupCategories.push(groupName);
    }
  }
  const hStep = Math.round(300 / (groupCategories.length - 1));
  for (var i = 0; i < groupCategories.length; i++) {
    groupColors.push(echarts.color.modifyHSL('#5A94DF', hStep * i));
  }
}

function getOption(data) {
  const lineStyle = {
    width: 0.5,
    opacity: 0.05
  };

  return {
    backgroundColor: '#333',
    tooltip: {
      padding: 10,
      backgroundColor: '#222',
      borderColor: '#777',
      borderWidth: 1
    },
    title: [
      {
        text: 'Groups',
        top: 0,
        left: 0,
        textStyle: {
          color: '#fff'
        }
      }
    ],
    visualMap: {
      show: true,
      type: 'piecewise',
      categories: groupCategories,
      dimension: indices.group,
      inRange: {
        color: groupColors //['#d94e5d','#eac736','#50a3ba']
      },
      outOfRange: {
        color: ['#ccc'] //['#d94e5d','#eac736','#50a3ba']
      },
      top: 20,
      textStyle: {
        color: '#fff'
      },
      realtime: false
    },
    parallelAxis: [
      { dim: 16, name: schema[16].name, scale: true, nameLocation: 'end' },
      { dim: 2, name: schema[2].name, nameLocation: 'end' },
      { dim: 4, name: schema[4].name, nameLocation: 'end' },
      { dim: 3, name: schema[3].name, nameLocation: 'end' },
      { dim: 5, name: schema[5].name, nameLocation: 'end' },
      { dim: 6, name: schema[6].name, nameLocation: 'end' },
      { dim: 7, name: schema[7].name, nameLocation: 'end' },
      { dim: 8, name: schema[8].name, nameLocation: 'end' },
      { dim: 9, name: schema[9].name, nameLocation: 'end' },
      { dim: 10, name: schema[10].name, nameLocation: 'end' },
      { dim: 11, name: schema[11].name, nameLocation: 'end' },
      { dim: 12, name: schema[12].name, nameLocation: 'end' },
      { dim: 13, name: schema[13].name, nameLocation: 'end' },
      { dim: 14, name: schema[14].name, nameLocation: 'end' },
      { dim: 15, name: schema[15].name, nameLocation: 'end' }
    ],
    parallel: {
      left: 280,
      top: 20,
      // top: 150,
      // height: 300,
      width: 400,
      layout: 'vertical',
      parallelAxisDefault: {
        type: 'value',
        name: 'nutrients',
        nameLocation: 'end',
        nameGap: 20,
        nameTextStyle: {
          color: '#fff',
          fontSize: 14
        },
        axisLine: {
          lineStyle: {
            color: '#aaa'
          }
        },
        axisTick: {
          lineStyle: {
            color: '#777'
          }
        },
        splitLine: {
          show: false
        },
        axisLabel: {
          color: '#fff'
        },
        realtime: false
      }
    },
    animation: false,
    series: [
      {
        name: 'nutrients',
        type: 'parallel',
        lineStyle: lineStyle,
        inactiveOpacity: 0,
        activeOpacity: 0.01,
        progressive: 500,
        smooth: true,
        data: data
      }
    ]
  };
}
"""#,
        option: [
            "backgroundColor": "#333",
            "tooltip": [
                "padding": 10.0,
                "backgroundColor": "#222",
                "borderColor": "#777",
                "borderWidth": 1.0
            ] as [String: Any],
            "title": [
                [
                    "text": "Groups",
                    "top": 0.0,
                    "left": 0.0,
                    "textStyle": ["color": "#fff"] as [String: Any]
                ] as [String: Any]
            ],
            "visualMap": [
                "show": true,
                "type": "piecewise",
                "categories": nutrientsNormalized.groups,
                "dimension": 1.0,                            // indices.group
                "inRange": ["color": nutrientsNormalized.colors] as [String: Any],
                "outOfRange": ["color": ["#ccc"]] as [String: Any],
                "top": 20.0,
                "textStyle": ["color": "#fff"] as [String: Any],
                "realtime": false
            ] as [String: Any],
            "parallelAxis": nutrientsParallelAxis,
            "parallel": [
                "left": 280.0,
                "top": 20.0,
                "width": 400.0,
                "layout": "vertical",
                "parallelAxisDefault": [
                    "type": "value",
                    "name": "nutrients",
                    "nameLocation": "end",
                    "nameGap": 20.0,
                    "nameTextStyle": ["color": "#fff", "fontSize": 14.0] as [String: Any],
                    "axisLine": ["lineStyle": ["color": "#aaa"] as [String: Any]] as [String: Any],
                    "axisTick": ["lineStyle": ["color": "#777"] as [String: Any]] as [String: Any],
                    "splitLine": ["show": false] as [String: Any],
                    "axisLabel": ["color": "#fff"] as [String: Any],
                    "realtime": false
                ] as [String: Any]
            ] as [String: Any],
            "animation": false,
            "series": [
                [
                    "name": "nutrients",
                    "type": "parallel",
                    "lineStyle": ["width": 0.5, "opacity": 0.05] as [String: Any],
                    "inactiveOpacity": 0.0,
                    "activeOpacity": 0.01,
                    "progressive": 500.0,
                    "smooth": true,
                    "data": nutrientsNormalized.rows as [Any]
                ] as [String: Any]
            ]
        ])
}
