// official-line-markline — replica of https://echarts.apache.org/examples/zh/editor.html?c=line-markline
// title: Line with Marklines / titleCN: 折线图的标记线
// A 5-point line series carrying a markLine whose data is generated in a loop: for each of the 12
// label `position` values, one horizontal y-axis markLine (labelled '{b}') plus — for every position
// except 'middle' — a two-point [start, end] markLine from coord [0, 0.3] to coord [3, 1]. The point
// of the example is to show every markLine label position side by side.
// DEVIATIONS:
//   - webOptionJS is the official source with only its TypeScript-isms removed (the
//     `: echarts.MarkLineComponentOption['data']` annotation, `as const`, the trailing `export {};`);
//     the generating loop itself runs verbatim in the page.
//   - The native pane cannot run that loop, so the same markLine data is generated by Swift
//     (`lineMarkLineData` below) with the identical formula — no values were hand-tweaked.
//   - Nothing is omitted: every formatter here is an ECharts template string ('{b}') or a plain
//     literal, never a JS closure, so the Swift option carries the example whole.
extension EChartsDemoRegistry {
    static let official_line_markline = EChartsDemo(
        name: "official-line-markline", category: "line",
        summary: "折线图的标记线 — Line with Marklines",
        width: 640, height: 420,
        nativeSupported: true,
        collection: .official,
        webOptionJS: #"""
const markLine = [];
const positions = [
  'start',
  'middle',
  'end',
  'insideStart',
  'insideStartTop',
  'insideStartBottom',
  'insideMiddle',
  'insideMiddleTop',
  'insideMiddleBottom',
  'insideEnd',
  'insideEndTop',
  'insideEndBottom'
];
for (var i = 0; i < positions.length; ++i) {
  markLine.push({
    name: positions[i],
    yAxis: 1.8 - 0.2 * Math.floor(i / 3),
    label: {
      formatter: '{b}',
      position: positions[i]
    }
  });

  if (positions[i] !== 'middle') {
    const name =
      positions[i] === 'insideMiddle' ? 'insideMiddle / middle' : positions[i];

    markLine.push([
      {
        name: 'start: ' + positions[i],
        coord: [0, 0.3],
        label: {
          formatter: name,
          position: positions[i]
        }
      },
      {
        name: 'end: ' + positions[i],
        coord: [3, 1]
      }
    ]);
  }
}

option = {
  animation: false,
  textStyle: {
    fontSize: 14
  },
  xAxis: {
    data: ['A', 'B', 'C', 'D', 'E'],
    boundaryGap: true,
    splitArea: {
      show: true
    }
  },
  yAxis: {
    max: 2
  },
  series: [
    {
      name: 'line',
      type: 'line',
      stack: 'all',
      symbolSize: 6,
      data: [0.3, 1.4, 1.2, 1, 0.6],
      markLine: {
        data: markLine,
        label: {
          distance: [20, 8]
        }
      }
    }
  ],
  grid: {
    top: 30,
    left: 60,
    right: 60,
    bottom: 40
  }
};
"""#,
        option: [
            "animation": false,
            "textStyle": [
                "fontSize": 14.0
            ] as [String: Any],
            "xAxis": [
                "data": ["A", "B", "C", "D", "E"],
                "boundaryGap": true,
                "splitArea": [
                    "show": true
                ] as [String: Any]
            ] as [String: Any],
            "yAxis": [
                "max": 2.0
            ] as [String: Any],
            "series": [
                [
                    "name": "line",
                    "type": "line",
                    "stack": "all",
                    "symbolSize": 6.0,
                    "data": [0.3, 1.4, 1.2, 1.0, 0.6],
                    "markLine": [
                        "data": lineMarkLineData,
                        "label": [
                            "distance": [20.0, 8.0]
                        ] as [String: Any]
                    ] as [String: Any]
                ] as [String: Any]
            ],
            "grid": [
                "top": 30.0,
                "left": 60.0,
                "right": 60.0,
                "bottom": 40.0
            ] as [String: Any]
        ])
}

// The 12 markLine label positions the example walks through.
private let lineMarkLinePositions: [String] = [
    "start",
    "middle",
    "end",
    "insideStart",
    "insideStartTop",
    "insideStartBottom",
    "insideMiddle",
    "insideMiddleTop",
    "insideMiddleBottom",
    "insideEnd",
    "insideEndTop",
    "insideEndBottom"
]

// Swift transcription of the official example's generating loop (see header). Elements are either a
// single mark-line spec ([String: Any] — a horizontal y-axis line) or a two-point one
// ([[String: Any]] — start/end coords), exactly as the JS array mixes them.
private let lineMarkLineData: [Any] = {
    var out: [Any] = []
    for (i, position) in lineMarkLinePositions.enumerated() {
        out.append([
            "name": position,
            "yAxis": 1.8 - 0.2 * Double(i / 3),
            "label": [
                "formatter": "{b}",
                "position": position
            ] as [String: Any]
        ] as [String: Any])

        if position != "middle" {
            let name = position == "insideMiddle" ? "insideMiddle / middle" : position
            let pair: [[String: Any]] = [
                [
                    "name": "start: " + position,
                    "coord": [0.0, 0.3],
                    "label": [
                        "formatter": name,
                        "position": position
                    ] as [String: Any]
                ],
                [
                    "name": "end: " + position,
                    "coord": [3.0, 1.0]
                ]
            ]
            out.append(pair)
        }
    }
    return out
}()
