// Ported from echarts/src/coord/cartesian/AxisModel.ts — keep in sync with upstream
/*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*/

import Foundation
import ZRenderKit
// import * as zrUtil from 'zrender/src/core/util';                    -> util.* (ZRenderKit)
// import ComponentModel from '../../model/Component';                 -> ComponentModel (model/Component.swift)
// import { AxisModelExtendedInCreator } from '../axisModelCreator';   -> AxisModelExtendedInCreator (coord/axisModelCreator.swift, T3)
// import {AxisModelCommonMixin} from '../axisModelCommonMixin';       -> AxisModelCommonMixin (coord/axisModelCommonMixin.swift, T2 protocol)
// import Axis2D from './Axis2D';                                      -> Axis2D (coord/cartesian/Axis2D.swift; PORT-NOTE: ported, but the local `axis` slot stays typed `Any`)
// import { AxisBaseOption } from '../axisCommonTypes';                -> AxisBaseOption (dynamic option bag, see axisModelCreator.swift; PORT-NOTE)
// import GridModel from './GridModel';                                -> GridModel (coord/cartesian/GridModel.swift; PORT-NOTE: ported, but `getCoordSysModel()` stays typed `Any?`)
// import { AxisBaseModel } from '../AxisBaseModel';                   -> AxisBaseModel (coord/AxisBaseModel.swift, T3)
// import { OrdinalSortInfo } from '../../util/types';                 -> OrdinalSortInfo (util/types.swift)
// import { SINGLE_REFERRING } from '../../util/model';                -> model.SINGLE_REFERRING (util/modelUtil.swift)

// upstream: export type CartesianAxisPosition = 'top' | 'bottom' | 'left' | 'right';
//   PORT-NOTE: no string unions in Swift → a `String` alias (option is read from the dynamic bag).
public typealias CartesianAxisPosition = String

// upstream:
// export type CartesianAxisOption = AxisBaseOption & {
//     gridIndex?: number;
//     gridId?: string;
//     position?: CartesianAxisPosition;
//     // Offset is for multiple axis on the same position.
//     offset?: number;
//     categorySortInfo?: OrdinalSortInfo;
// };
//   PORT-NOTE: option interfaces are modeled as the dynamic option bag ([String: Any]) per the
//   option-tree convention (`AxisBaseOption` is already `[String: Any]`, see axisModelCreator.swift).
//   The extra fields (gridIndex/gridId/position/offset/categorySortInfo) are keyed accesses on the bag.
public typealias CartesianAxisOption = AxisBaseOption

// upstream: export type XAXisOption = CartesianAxisOption & { mainType?: 'xAxis' };
public typealias XAXisOption = CartesianAxisOption
// upstream: export type YAXisOption = CartesianAxisOption & { mainType?: 'yAxis' };
public typealias YAXisOption = CartesianAxisOption

// upstream:
// export class CartesianAxisModel extends ComponentModel<CartesianAxisOption>
//     implements AxisBaseModel<CartesianAxisOption> {
//
// PORT-NOTE: upstream `extends ComponentModel` and `implements AxisBaseModel` (a TS interface that
//   declaration-merges ComponentModel + AxisModelCommonMixin + AxisModelExtendedInCreator + `axis`).
//   Per CONVENTIONS §2, mixins are ported as protocol + protocol-extension: the class extends the real
//   `ComponentModel` reference type and conforms to the `AxisModelCommonMixin` protocol (which supplies
//   `needIncludeZero()` / `getCoordSysModel()` via its extension — this replaces
//   `zrUtil.mixin(CartesianAxisModel, AxisModelCommonMixin)` below). The `axis` member is declared here.
//   `AxisModelExtendedInCreator` (getCategories / getOrdinalMeta / updateAxisBreaks) is NOT implemented
//   on this class in upstream either — those come from the subclass generated by `axisModelCreator`
//   (coord/axisModelCreator.swift), so they are not redeclared here.
// PORT-NOTE: not `final` — upstream subclasses it (passed as `BaseAxisModelClass` to
//   `axisModelCreator`; the generated per-type axis model extends it). Per CONVENTIONS §2, reference
//   types that are subclassed upstream stay open to subclassing.
// PORT-NOTE (INTEGRATION): upstream `class CartesianAxisModel extends ComponentModel implements
//   AxisBaseModel<CartesianAxisOption>`. `AxisBaseModel` is a TS interface (structural), but the Swift
//   port models it as a real `open class AxisBaseModel: ComponentModel, AxisModelCommonMixin`. Since
//   `Axis.model` is typed `AxisBaseModel` and consumers (Grid, axisHelper.isAxisOnBand) require it,
//   `CartesianAxisModel` subclasses `AxisBaseModel` here (inheriting ComponentModel + the
//   AxisModelCommonMixin conformance + the `axis` slot). The former standalone `_axis`/`axis` members
//   are removed in favor of the base class ones.
public class CartesianAxisModel: AxisBaseModel {

    // static type = 'cartesian2dAxis';
    public override class var type: ComponentFullType { return "cartesian2dAxis" }

    // getCoordSysModel(): GridModel {
    //     return this.getReferringComponents('grid', SINGLE_REFERRING).models[0] as GridModel;
    // }
    //
    // PORT-NOTE: upstream returns `GridModel` (ported at coord/cartesian/GridModel.swift); the
    //   `AxisModelCommonMixin.getCoordSysModel()` protocol requirement returns `Any?` (Swift protocol
    //   witnesses can't narrow the return), so `models[0]` (a `ComponentModel`) is returned as-is and
    //   callers cast to `GridModel` at the use site (e.g. CartesianAxisView).
    public func getCoordSysModel() -> Any? {
        return self.getReferringComponents("grid", model.SINGLE_REFERRING).models[0]
    }

}

// upstream:
// export interface CartesianAxisModel extends AxisModelCommonMixin<CartesianAxisOption>,
//     AxisModelExtendedInCreator {}
//
// zrUtil.mixin(CartesianAxisModel, AxisModelCommonMixin);
//   -> Modeled by the `AxisModelCommonMixin` protocol conformance on the class above (its extension
//      grafts `needIncludeZero()` / `getCoordSysModel()`). `AxisModelExtendedInCreator` is provided by
//      the axisModelCreator-generated subclass, not this base (see class-level PORT-NOTE above).

// export default CartesianAxisModel;  -> `public final class CartesianAxisModel` above.
