// Ported from echarts/src/coord/AxisBaseModel.ts — keep in sync with upstream
/*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*/

/**
 * Base Axis Model for xAxis, yAxis, angleAxis, radiusAxis. singleAxis
 */
import Foundation
// import { AxisBaseOptionCommon } from './axisCommonTypes';           -> AxisBaseOptionCommon
//     (coord/axisCommonTypes.swift; PORT-TODO: option interfaces not yet ported — the generic
//     `Opt` is dropped per CONVENTIONS §2, the option tree is the dynamic `Any` bag on Model)
// import ComponentModel from '../model/Component';                     -> ComponentModel (model/Component.swift)
// import { AxisModelCommonMixin } from './axisModelCommonMixin';       -> AxisModelCommonMixin (coord/axisModelCommonMixin.swift, T2 protocol)
// import { AxisModelExtendedInCreator } from './axisModelCreator';     -> AxisModelExtendedInCreator
//     (coord/axisModelCreator.swift; PORT-TODO: not yet ported this phase — conformance deferred, see below)
// import Axis from './Axis';                                          -> Axis (coord/Axis.swift; PORT-TODO: not yet ported — typed `Any`)

// upstream:
// export interface AxisBaseModel<T extends AxisBaseOptionCommon = AxisBaseOptionCommon>
//     extends ComponentModel<T>,
//     AxisModelCommonMixin<T>,
//     AxisModelExtendedInCreator {
//
//     axis: Axis;
// }
//
// PORT-TODO: upstream `AxisBaseModel` is a pure TS interface that merges the `ComponentModel`
//   class with the `AxisModelCommonMixin` (interface+class declaration-merge) and the
//   `AxisModelExtendedInCreator` interface; the concrete class is produced by `axisModelCreator`.
//   Per CONVENTIONS §2 (classes → reference types where upstream subclasses), it is ported as an
//   `open class` extending the real `ComponentModel` reference type so the axis models generated by
//   `axisModelCreator` (and hand-written ones such as CartesianAxisModel — Phase 6b) can subclass
//   it. It conforms to the `AxisModelCommonMixin` protocol (which supplies `needIncludeZero()` /
//   `getCoordSysModel()` via its protocol extension).
//
// PORT-TODO: `AxisModelExtendedInCreator` (coord/axisModelCreator.ts) is not yet ported this phase,
//   so its method set — `getCategories(rawData?)`, `getOrdinalMeta()`, `updateAxisBreaks(payload)` —
//   is NOT redeclared here (those members belong to `axisModelCreator.swift`, not this file).
//   Reinstate `, AxisModelExtendedInCreator` in the conformance list once that sibling lands.
open class AxisBaseModel: ComponentModel, AxisModelCommonMixin /*, AxisModelExtendedInCreator */ {

    // axis: Axis;
    //
    // PORT-TODO: upstream types this `Axis` (coord/Axis.ts not yet ported). Modeled as `Any`, backed
    //   by an optional so it can be assigned during axis creation while satisfying the
    //   `AxisModelCommonMixin.axis: Any` requirement (a non-optional getter). Re-narrow to `Axis`
    //   once coord/Axis.swift lands.
    private var _axis: Any?
    public var axis: Any {
        get { return _axis! }
        set { _axis = newValue }
    }

    // upstream: `AxisBaseModel` (interface) extends `AxisModelExtendedInCreator`, whose concrete impl
    //   is produced by `axisModelCreator` (the generated `AxisModel` subclass). `getCategories` is
    //   declared here as an `open` base member (dynamically dispatched) so consumers typed against
    //   `AxisBaseModel` (e.g. scaleRawExtentInfo) resolve to the subclass override at runtime; the
    //   base default returns nil (non-category / not-yet-populated axes).
    // PORT-TODO: full `AxisModelExtendedInCreator` conformance (getOrdinalMeta / updateAxisBreaks) is
    //   provided by the generated `AxisModel`; only `getCategories` is needed on the base surface here.
    open func getCategories(_ rawData: Bool? = nil) -> [OrdinalRawValue]? {
        _ = rawData
        return nil
    }
}
